#!/bin/bash -e

rm -rf riot-web matrix-react-sdk

git clone https://github.com/liquidinvestigations/matrix-react-sdk
( cd matrix-react-sdk; git checkout liquid )

git clone https://github.com/vector-im/riot-web
( cd riot-web; git checkout v0.13.5 )

(
  cd matrix-react-sdk
  git checkout liquid
  npm install
  npm run build
)

(
  cd riot-web
  npm install
  (
    cd node_modules
    rm -rf matrix-react-sdk
    ln -s ../../matrix-react-sdk
  )
  npm run dist
)
mv riot-web/dist/riot-v0.13.5-dirty.tar.gz ./riot-liquid.tar.gz
